spring:
  datasource:
    url: jdbc:h2:mem:bookstoremanager_dev;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        format-sql: false
  h2:
    console:
      enable: false
logging:
  level:
    br:
      com:
        bookstore manager: INFO